### ISSUE TITLE
[FIX] Error: Cannot find module 'edit-json-file'

### ISSUE THREAD

**Issue by HenriqueSilverio** [Appsweet-co/npm-carbon#7]
**Describe the bug**
Can't use any of lib commands.

**To Reproduce**
1. Run `--help` (or any other `npm-carbon` command).

```bash
npx @appsweet-co/npm-carbon --help
```

**Expected behavior**
Prints a full list of commands.

**Current behavior**
Throws `MODULE_NOT_FOUND` error.

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'edit-json-file'
Require stack:
- /Users/henrique/.npm/_npx/79a9db710315dff0/node_modules/@appsweet-co/npm-carbon/bin/cli.js
- /Users/henrique/.npm/_npx/79a9db710315dff0/node_modules/@appsweet-co/npm-carbon/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/henrique/.npm/_npx/79a9db710315dff0/node_modules/@appsweet-co/npm-carbon/bin/cli.js:17:40)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/henrique/.npm/_npx/79a9db710315dff0/node_modules/@appsweet-co/npm-carbon/bin/cli.js',
    '/Users/henrique/.npm/_npx/79a9db710315dff0/node_modules/@appsweet-co/npm-carbon/bin/index.js'
  ]
}
```

**Desktop:**
 - OS: macOS Big Sur (11.5.2)
 - Node.js: 16.15.0
 - npm: 8.5.5

**Comment by dperuo** [comment]
Got it!

**Comment by dperuo** [comment]
@HenriqueSilverio - We'll let you know when the fix goes live

**Comment by dperuo** [comment]
May or may not be related to breaking changes in Node v16.

**Comment by HenriqueSilverio** [comment]
@dperuo What's the Node (and npm) version that you tested the lib against and was worked?

I tried to run with "node v14.19.2 (npm v6.14.17)" and "node v12.22.12 (npm v6.14.16)", and the same errors occurred.

### node v16.15.0 (npm v8.5.5)

```bash
npx @appsweet-co/npm-carbon --help
```

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'edit-json-file'
Require stack:
- /Users/henrique/.npm/_npx/79a9db710315dff0/node_modules/@appsweet-co/npm-carbon/bin/cli.js
- /Users/henrique/.npm/_npx/79a9db710315dff0/node_modules/@appsweet-co/npm-carbon/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/henrique/.npm/_npx/79a9db710315dff0/node_modules/@appsweet-co/npm-carbon/bin/cli.js:17:40)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/henrique/.npm/_npx/79a9db710315dff0/node_modules/@appsweet-co/npm-carbon/bin/cli.js',
    '/Users/henrique/.npm/_npx/79a9db710315dff0/node_modules/@appsweet-co/npm-carbon/bin/index.js'
  ]
}
```

### node v14.19.2 (npm v6.14.17)

```bash
npx @appsweet-co/npm-carbon --help
```

```
Cannot find module 'edit-json-file'
Require stack:
- /Users/henrique/.npm/_npx/82534/lib/node_modules/@appsweet-co/npm-carbon/bin/cli.js
- /Users/henrique/.npm/_npx/82534/lib/node_modules/@appsweet-co/npm-carbon/bin/index.js
```

### node v12.22.12 (npm v6.14.16)

```bash
npx @appsweet-co/npm-carbon --help
```

```
Cannot find module 'edit-json-file'
Require stack:
- /Users/henrique/.npm/_npx/82992/lib/node_modules/@appsweet-co/npm-carbon/bin/cli.js
- /Users/henrique/.npm/_npx/82992/lib/node_modules/@appsweet-co/npm-carbon/bin/index.js
```

**Comment by dperuo** [comment]
@HenriqueSilverio - You might be correct. There's something about this `edit-json-file` dependency.

We don't use the `edit-json-file` dependency directly. Looks like TypeScript adds it during compile time.

**Comment by dperuo** [comment]
@HenriqueSilverio - I think we fixed the issue. Please install `v1.0.12` and let me know how it goes.

- https://github.com/Appsweet-co/npm-carbon/releases/tag/v1.0.12
- https://www.npmjs.com/package/@appsweet-co/npm-carbon/v/1.0.12

Please open a new ticket if you still have issues.
